/**
 * AI Career Guidance Assistant - Prompt Injector Engine & Markdown Formatter
 * Combines System Prompt + Embedded Knowledge Base JSON + User Variables
 * Renders response according to strict Markdown specification.
 */

import { UserInput, CareerBranch, ValidationResult } from '../types';
import { GROUNDING_KNOWLEDGE_BASE } from './knowledgeBase';

export function constructInjectedPrompt(input: UserInput): string {
  return `SYSTEM ROLE & INSTRUCTION SET: AI Career Guidance Assistant (Prototype Engine)

[SYSTEM METADATA]
Architecture Strategy: Monolithic Zero-Backend Single-Turn Engine
Reasoning Engine: Simulated Tree of Thoughts (ToT)
Grounding Strategy: Embedded In-Memory Knowledge Base
Primary Target: High-Accuracy Multi-Domain Career Mapping

[GROUNDING KNOWLEDGE BASE (IN-MEMORY JSON)]
${JSON.stringify(GROUNDING_KNOWLEDGE_BASE, null, 2)}

[INPUT SCHEMA VALIDATION]
Analyze the provided user input against the required payload structure below. If any critical fields (Academic Marks, Interests, Education Level) are missing or invalid, immediately halt processing and render the missing input error state.

USER INPUT SCHEMA:
1. 10th Marks/Grades: ${input.grade_10th}
2. 12th Marks & Core Subjects: ${input.grade_12th_subjects}
3. Education Level / Degree: ${input.education_level}
4. Current Technical & Soft Skills: ${input.current_skills}
5. Expressed Interests & Hobbies: ${input.interests}
6. Target Industry / Field: ${input.target_industry}
7. Preferred Work-Life Balance (1-10 Scale): ${input.wlb_preference}
8. Target Salary Expectation: ${input.salary_range}

[EXECUTION WORKFLOW: SIMULATED TREE OF THOUGHTS (ToT)]
Execute the following reasoning phases sequentially before producing the final output:

PHASE 1: THOUGHT TREE GENERATION
- Generate 3 distinct candidate career paths (Branch A, Branch B, Branch C) based on the user's multi-domain input.
- Branch A: Direct fit to explicit target industry and educational background.
- Branch B: Skill-adjacent path leveraging cross-disciplinary strengths (e.g., STEM + Law -> IP Law, Language + Tech -> NLP).
- Branch C: Emerging or unconventional path based on expressed interests and skills.

PHASE 2: CANDIDATE EVALUATION MATRIX
- Evaluate each branch against the following scoring criteria (Scale 0–100):
  * Academic & Skill Fit
  * Interest & Value Alignment
  * Work-Life Balance Feasibility
  * Salary Expectation Match
- Compute a weighted composite score for each branch using the weights defined in the Knowledge Base.

PHASE 3: SELECTION & GUARDRAIL ENFORCEMENT
- Guardrail 1 (Multi-Option Safety): Select the top 2 scored candidates to avoid single-option bias.
- Guardrail 2 (Uncertainty & Hallucination Avoidance): Explicitly flag any skill or academic gaps that require upskilling. Do not guarantee employment outcomes or state absolute salary promises.
- Guardrail 3 (Human Verification): State clearly that this output is for educational decision-support only and requires user review.

[OUTPUT SPECIFICATION]
Render the response using the strict Markdown template below. Do not add conversational fluff, system greetings, or meta-commentary outside the structure.
`;
}

export function formatStrictMarkdownReport(
  validation: ValidationResult,
  branches: CareerBranch[],
  top2: CareerBranch[]
): string {
  if (!validation.passed) {
    return `### 1. INPUT VALIDATION STATUS
- **Status:** FAILED
- **Validation Notes:** ${validation.validationNotes}

### 2. REASONING MATRIX (Tree of Thoughts Evaluation)
*Processing halted: Missing required critical fields.*

### 3. RECOMMENDED CAREER OPTIONS
*No recommendations can be generated until required input fields are provided.*

### 4. RESPONSIBLE AI & GUARDRAIL DISCLOSURES
- **Decision Support Disclaimer:** This guidance is generated by an automated AI model for informational purposes only and does not constitute formal career counseling or guaranteed career success.
- **Human Verification Required:** Please review these options with a qualified academic advisor or career professional before making financial or educational commitments.`;
  }

  const branchA = branches.find(b => b.branchId === 'Branch A') || branches[0];
  const branchB = branches.find(b => b.branchId === 'Branch B') || branches[1];
  const branchC = branches.find(b => b.branchId === 'Branch C') || branches[2];

  const opt1 = top2[0] || branchA;
  const opt2 = top2[1] || branchB;

  return `### 1. INPUT VALIDATION STATUS
- **Status:** PASSED
- **Validation Notes:** ${validation.validationNotes}

### 2. REASONING MATRIX (Tree of Thoughts Evaluation)
| Candidate Path | Academic & Skill Score (35%) | Interest Fit (20%) | WLB Fit (10%) | Salary Fit (10%) | Overall Composite Score |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **Branch A:** ${branchA.roleName} | ${branchA.academicAndSkillScore} | ${branchA.interestFitScore} | ${branchA.wlbFitScore} | ${branchA.salaryFitScore} | **${branchA.compositeScore.toFixed(1)}** |
| **Branch B:** ${branchB.roleName} | ${branchB.academicAndSkillScore} | ${branchB.interestFitScore} | ${branchB.wlbFitScore} | ${branchB.salaryFitScore} | **${branchB.compositeScore.toFixed(1)}** |
| **Branch C:** ${branchC.roleName} | ${branchC.academicAndSkillScore} | ${branchC.interestFitScore} | ${branchC.wlbFitScore} | ${branchC.salaryFitScore} | **${branchC.compositeScore.toFixed(1)}** |

### 3. RECOMMENDED CAREER OPTIONS

#### Option 1: ${opt1.roleName} (${opt1.branchType} - ${opt1.branchId})
- **Domain:** ${opt1.domainLabel}
- **Fit Justification:** ${opt1.fitJustification}
- **Upskilling & Bridge Requirements:** ${opt1.upskillingAndBridge.join("; ")}
- **Expected WLB & Market Alignment:** ${opt1.expectedWLBAndMarket}

#### Option 2: ${opt2.roleName} (${opt2.branchType} - ${opt2.branchId})
- **Domain:** ${opt2.domainLabel}
- **Fit Justification:** ${opt2.fitJustification}
- **Upskilling & Bridge Requirements:** ${opt2.upskillingAndBridge.join("; ")}
- **Expected WLB & Market Alignment:** ${opt2.expectedWLBAndMarket}

### 4. RESPONSIBLE AI & GUARDRAIL DISCLOSURES
- **Decision Support Disclaimer:** This guidance is generated by an automated AI model for informational purposes only and does not constitute formal career counseling or guaranteed career success.
- **Human Verification Required:** Please review these options with a qualified academic advisor or career professional before making financial or educational commitments.`;
}
